### ISSUE TITLE
Make fluentd cloudwatch compatible

### ISSUE THREAD

**Issue by nohant** [sighupio/fury-kubernetes-logging#102]
In some cases we need to send log to cloudwatch from fluentd.
This feature is missing in our images since _quay.io/sighup/fluentd:v1.11.5-debian-1.0_. 
Do you think it will be possible to have it back for the latest modules of logging v1 and v2?

**Comment by nutellinoit** [comment]
Hi Greg, Cloudwatch output is already available with the logging operator, on module versions v2 and v3

https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/cloudwatch/

**Comment by nohant** [comment]
thank you so much, so we only have to update to the V2 the cluster which are still on the v1 and can't send anymore the logs to clouwatch.

Thank you, will close the issue.
