### ISSUE TITLE
[v3.0.1] deprecated CONTRIBUTING docs

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/fury-kubernetes-logging#106]
Please update the [CONTRIBUTING](https://github.com/sighupio/fury-kubernetes-logging/blob/v3.0.1/docs/CONTRIBUTING.md) docs for version >= 3.0.0 because ElasticSearch has been deprecated.

**Comment by ralgozino** [comment]
There's an ongoing conversation about this on #78

**Comment by nutellinoit** [comment]
Closing, we will address this problem in a global documentation refactoring
