### ISSUE TITLE
Grafana monitoring: exceeded max resolution 11000 points in timeseries

### ISSUE THREAD

**Issue by andrearota** [sighupio/fury-kubernetes-logging#16]
Hello, when I select a time interval larger than 2 days in Grafana, I get the following error.

![image](https://user-images.githubusercontent.com/883826/89193789-c97e3380-d5a6-11ea-9d5f-941ade25ee15.png)

Is there a way to handle at least a week of data (e.g. we would like to monitor one week of ingress traffic)?

Thank you!

**Comment by iknite** [comment]
link to a discussion related to the prometheus hard-limit

https://github.com/prometheus/prometheus/issues/2253

**Comment by iknite** [comment]
The issue is happening in `1.3.0` and it's fixed on later versions (we tried `1.5.0` and it's working) we recommend to update the cluster for this case.

**Comment by andrearota** [comment]
Thank you @iknite, we are going to update with @nutellinoit's help and let you know.
