### ISSUE TITLE
The elasticsearch_exporter image in use has been deprecated 

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-kubernetes-logging#168]
The image we are using for exporting opensearch metrics in prometheus format:

https://github.com/sighupio/fury-kubernetes-logging/blob/5a3e416aa1c2849785b5e7a90586ccb534c32e02/katalog/opensearch-single/kustomization.yaml#L12-L14

has been updated 5 years ago for the last time:

https://hub.docker.com/r/justwatch/elasticsearch_exporter/tags

(it also is not build for ARM architectures)

**Comment by lukeskywlkr** [comment]
This issue is set to be closed once we release v4.0.0. See #175
