### ISSUE TITLE
Some important cerebro metrics are not container aware.

### ISSUE THREAD

**Issue by Reuenthal767** [sighupio/fury-kubernetes-logging#17]
Metrics exposed by cerebro such as:
- process cpu % (nodes tab)
- os cpu (nodes tab)
- ram.percent (cat apis/nodes)

are not container aware and thus highly misleading (I've digged into the angularjs and play scala source code to confirm this).

Another problem is that there is no way of viewing any kind of historical data regarding metrics exposed by cerebro.

My proposed solution is to enable kibana xpack monitoring: "xpack.monitoring.collection.enabled" : "true" with container aware metrics: "xpack.monitoring.ui.container.elasticsearch.enabled" : "true" (the second setting should be set to true by default in the ES docker container)

This change will enable the "Monitoring" tab in Kibana and will create 2 special indices with 1shard and 1replica:

- .monitoring-es-6-yyyy.mm.dd
- .monitoring-kibana-6-yyyy.mm.dd

This indices come with an Index Lifecycle Policy (ILM) attached and are automatically deleted after 7 days.
In the basic license version you cannot set a retention that exceed 7 days.
If lower retention is needed a curator job that takes in consideration that there is already an ILM attached to the indices will need to be created.

**Comment by nutellinoit** [comment]
Hi @Reuenthal767 , is this issue still relevant?

**Comment by nutellinoit** [comment]
Hi @Reuenthal767 , would you like to issue a PR to the upstream project? 

If not, we should close this issue
