### ISSUE TITLE
Add livenessProbe to fluentd DaemonSet

### ISSUE THREAD

**Issue by lnovara** [sighupio/fury-kubernetes-logging#2]
fluentd is lacking a proper livenessProbe.

See
- https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L58
- https://docs.fluentd.org/v0.12/articles/monitoring#process-monitoring

for implementation ideas.

**Comment by angelbarrera92** [comment]
addressed in #12  -> https://github.com/sighupio/fury-kubernetes-logging/pull/12/commits/2cf7820b22ff1417338d46d1dbda11284471f45c
Idea from upstream fluentd helm stable chart

**Comment by lnovara** [comment]
Closing since #12 was merged.
